name: sample_sd_2.1-astronaut

subtask: None

task:
  prompt: "a photo of an astronaut riding a horse on mars"

  height: 512
  width: 512

  # SD
  num_inference_step: 25
  guidance_scale: 7.5
  negative_prompt: "low quality, blurry, ugly, oversaturated"

sample:
  save_sample: True
  sample_root_path: "./tmp/sample_sd_2.1"
